### ISSUE TITLE
Support for pretty printing JSON?

### ISSUE THREAD

**Issue by nm-harry** [nutmegdevelopment/marathon-config-generator#3]
Could it be possible to add a flag at runtime to get config-generator to pretty print json?

Would be useful in jenkins to see what was generated without pasting into a text editor.

**Comment by tompave-nutmeg** [comment]
In the past I've grabbed the [jq](https://stedolan.github.io/jq/) binary, copied somewhere on the jenkins box, and piped through it to get pretty printed JSON.

**Comment by nm-harry** [comment]
Yeah, is a good idea, been doing that locally with jsontool (npm) but I would be hesitant to add more tools and binaries into the already beefy jenkins slave docker containers. 

Was hoping that there is a flag/option in go to just pretty print the output.

**Comment by jfindley** [comment]
No need to do any of this.  Just use MarshalIndent rather than Marshal and it will be "pretty".  See https://godoc.org/encoding/json#MarshalIndent

**Comment by nm-harry** [comment]
I don't have permission to commit to this repo - so here is my change. I've tried it with YML files and produces nice, indented output.

```go
// ToJSON returns a JSON string representation of itself.
func (t *MarathonApp) ToJSON() string {
	jsonString, err := json.MarshalIndent(t, "", "  ")
	if err != nil {
		log.Fatalf("Error marshalling JSON: %s", err.Error())
	}
	return string(jsonString[:])
}
```

**Comment by nm-harry** [comment]
I think it should be a flag that sets nice formatted output and default is non-indented.

**Comment by jfindley** [comment]
wouldn't you always want it indented?

**Comment by nm-harry** [comment]
Yes, I do, just not sure everyone else does. 

120ebf9e86234c2b9792d6aa3ed4febf302c2404 - commit to add indenting. Have tested locally and is much easier to read.
